### PR TITLE
zlib process support

### PR DESCRIPTION
**Pull request by MegaPiggy**

### CODE REVIEW

**Review by generalmimon — CHANGES_REQUESTED** [review]
I believe that vendoring sources is an anti-pattern and it's not something I would endorse in Kaitai Struct repos. You should add https://github.com/zerkman/zzlib as a Git submodule instead. Read https://github.com/kaitai-io/kaitai_struct_lua_runtime/pull/5#discussion_r495541909 for more info.

**Comment by KOLANICH** [comment]
They should not be used as a submodule, instead they should be used from a package manager. Also, decompressors live in kaitai_compress repo. And also, it may make sense to make sure that the API is compatible to https://github.com/kaitaiStructCompile/kaitai_compress/blob/python_fixes/python/kaitai/compress/algorithms/zlib.py .

**Comment by MegaPiggy** [comment]
If I add it as a submodule, the `require`s inside the main zzlib file will not work correctly.
Is there a way to commit edits to submodules?

**Comment by MegaPiggy** [comment]
🤔

**Comment by generalmimon** [comment]
@MegaPiggy @Qix- Could you look at my latest changes here? The `zzlib` submodule has to be in the include path for `require()`, so I tried to temporarily add it there at runtime. Misusing `debug.getinfo()` to get the script path feels incorrect, but I haven't found any better solution.

Of course, it would be much easier for us to pass the burden of adding the `zzlib/` directory to `LUA_PATH` to users, but I don't like that - ideally, the runtime lib should be able to load `zzlib` itself.

**Review by MegaPiggy — COMMENTED** [review]
I think this is the best solution for now.

**Review by generalmimon — APPROVED** [review]
@MegaPiggy 

> I think this is the best solution for now.

Thanks for checking and for the contribution!

**Pull request merged**
